### ISSUE TITLE
 About the truth NA12878 b19 vcf file

### ISSUE THREAD

**Issue by jackycsie** [bcbio/bcbio_validations#4]
Hi team,

Do you know where can I find trush NA12878 b19 vcf file ?

I find very long, but still can't find it.

Thanks, jacky

**Comment by chapmanb** [comment]
Jacky;
Thanks for the question. These files are distributed by the Genome in a Bottle project here:

https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv3.3.2/GRCh37/

The recipe that downloads and organized them in bcbio is here:

https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg19/giab-NA12878.yaml

Hope this helps.
