### ISSUE TITLE
Validation of duplications for huref sample

### ISSUE THREAD

**Issue by golubnikova** [bcbio/bcbio_validations#5]
Hi!

Thank you for your [README](https://github.com/bcbio/bcbio_validations/tree/master/huref_sv)
Are you planning to add the calculation of precision and sensitivity for duplications (DUP)?

**Comment by naumenko-sa** [comment]
No, unfortunately, I am not - I don't have any SV related projects currently, and I've lost the access to the HuRef validation files.
Here are some fresh validations based on NIST
https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkac039/6517943?login=false

Please post issues to https://github.com/bcbio/bcbio-nextgen/issues, here they will get lost.

**Comment by golubnikova** [comment]
Thank you!
